name: GitHub Trophy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Trophy
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: sunilmohanty23
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight

      - name: Commit Trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git diff --cached --quiet || git commit -m "Update GitHub trophies"
          git push
